apiVersion: v1
kind: ConfigMap
metadata:
  name: metastore-initdb
data:
  init.sh: |
    mysql -u root -p${MYSQL_ROOT_PASSWORD} <<EOF
      CREATE DATABASE IF NOT EXISTS metastore; 
      CREATE USER 'hive'@'%' IDENTIFIED WITH mysql_native_password BY '${HIVE_USER_PWD}';
      GRANT ALL PRIVILEGES ON metastore . * TO 'hive'@'%';    
    EOF
