apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-warehouse-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/warehouse"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-warehouse-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
