apiVersion: apps/v1
kind: Deployment
metadata:
  name: metastore2
spec:
  selector:
    matchLabels:
      app: metastore2
  template:
    metadata:
      labels:
        app: metastore2
    spec: 
      initContainers:
        - name: check-mysql
          image: busybox
          command:
            - sh
            - -c
            - nc -vz mysql 3306
      containers:
        - name: metastore2
          image: spark-thrift-server:0.1.0
          imagePullPolicy: Never
          command:
            - /opt/init.sh
          ports:
            - name: metastore
              containerPort: 9083
          volumeMounts:
            - name: metastoreinit
              mountPath: /opt/init.sh
              subPath: init.sh
          env:
            - name: HIVE_CONF_DIR
              value: /opt/spark/conf
            - name: HIVE_USER_PWD
              valueFrom:
                secretKeyRef:
                  name: hive
                  key: password
          livenessProbe:
            tcpSocket:
              port: metastore
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: metastore
            failureThreshold: 6
            periodSeconds: 20
      volumes:
        - name: metastoreinit
          configMap:
            name: metastore-initstore
            defaultMode: 0777
---
apiVersion: v1
kind: Service
metadata:
  name: metastore2
spec:
  selector:
    app: metastore2
  ports:
    - port: 9083
      targetPort: 9083 