apiVersion: v1
kind: ConfigMap
metadata:
  name: metastore-initstore
data:
  init.sh: |
      #!/bin/bash
      schematool -validate -dbType mysql -passWord ${HIVE_USER_PWD}

      if [ $? -gt 0 ]; then
              schematool -initSchema -dbType mysql -passWord ${HIVE_USER_PWD}
      fi

      hive --service metastore -hiveconf javax.jdo.option.ConnectionPassword=${HIVE_USER_PWD}
